In [1]:
import os
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn import cross_validation, metrics
import xgboost

C:\Users\WHUANG07\AppData\Local\Continuum\Anaconda2\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

WindowsError: [Error 126] The specified module could not be found

## Exploratory Analysis

In [2]:
os.chdir('C:/Dentsu/Code 1 Infinity/Infinity Reboot/codes/test')
data = pd.read_csv('data/Uber Marketing Analyst DriverData.csv')
data.head(10)
# data.describe()

,id,city_name,signup_os,signup_channel,signup_date,bgc_date,vehicle_added_date,vehicle_make,vehicle_model,vehicle_year,first_completed_date
0,1,Strark,ios web,Paid,1/2/16,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Strark,windows,Paid,1/21/16,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Wrouver,windows,Organic,1/11/16,1/11/16,NaN,NaN,NaN,NaN,NaN
3,4,Berton,android web,Referral,1/29/16,2/3/16,2/3/16,Toyota,Corolla,2016.0,2/3/16
4,5,Strark,android web,Referral,1/10/16,1/25/16,1/26/16,Hyundai,Sonata,2016.0,NaN
5,6,Strark,android web,Referral,1/18/16,1/18/16,1/22/16,Cadillac,DTS,2006.0,NaN
6,7,Strark,ios web,Paid,1/14/16,1/16/16,1/21/16,Toyota,Prius V,2014.0,1/23/16
7,8,Strark,ios web,Referral,1/26/16,2/5/16,NaN,NaN,NaN,NaN,NaN
8,9,Strark,NaN,Referral,1/5/16,NaN,NaN,NaN,NaN,NaN,NaN
9,10,Berton,ios web,Paid,1/25/16,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data.shape

(54681, 11)

In [4]:
def _exploratory_analysis_string(column_name):
    num_null = data[column_name].isnull().sum()
    print 'Number of Missing values for '+column_name+': %d'%num_null
    print 'Frequency Table for '+column_name+' :' 
    return data[column_name].value_counts()

In [5]:
_exploratory_analysis_string('city_name')

Number of Missing values for city_name: 0
Frequency Table for city_name :

Strark     29557
Berton     20117
Wrouver     5007
Name: city_name, dtype: int64

In [6]:
_exploratory_analysis_string('signup_os')

Number of Missing values for signup_os: 6857
Frequency Table for signup_os :

ios web        16632
android web    14944
windows         6776
mac             5824
other           3648
Name: signup_os, dtype: int64

In [7]:
_exploratory_analysis_string('signup_channel')

Number of Missing values for signup_channel: 0
Frequency Table for signup_channel :

Paid        23938
Referral    17316
Organic     13427
Name: signup_channel, dtype: int64

In [8]:
_exploratory_analysis_string('vehicle_make')

Number of Missing values for vehicle_make: 41458
Frequency Table for vehicle_make :

Toyota           3219
Honda            1845
Nissan           1311
Ford              778
Hyundai           677
Chevrolet         665
Kia               584
Volkswagen        503
Dodge             393
Mercedes-Benz     348
Lexus             335
BMW               330
Mazda             292
Subaru            221
Jeep              203
Chrysler          202
Acura             190
Scion             164
Infiniti          147
Audi              144
Mitsubishi        113
GMC                89
Cadillac           86
Lincoln            70
Volvo              57
Buick              46
Saturn             30
Pontiac            30
Land Rover         20
Mini               20
Jaguar             15
Tesla              13
Suzuki             12
Fiat               11
Porsche            10
Mercury             9
Autobot             8
Saab                7
Hummer              7
Bike                6
Bicycle             5
Bentley             2
Maserati            2
Isuzu               2
Oldsmobile          1
Walker              1
Name: vehicle_make, dtype: int64

In [9]:
_exploratory_analysis_string('vehicle_model')

Number of Missing values for vehicle_model: 41458
Frequency Table for vehicle_model :

Civic                   689
Corolla                 688
Camry                   683
Accord                  595
Prius V                 522
Altima                  422
Prius                   369
Sentra                  330
Sonata                  259
Elantra                 255
Optima                  212
Jetta                   205
CR-V                    193
Versa                   192
RAV4                    189
Fusion                  186
3-series                163
Focus                   158
Sienna                  154
MAZDA3                  146
C-Class                 145
Malibu                  127
Passat                  120
Prius C                 118
Soul                    117
Odyssey                 113
Cruze                   109
Escape                  107
Highlander              106
Rogue                   103
                       ...
CLK-Class                 1
Venture                   1
QX50                      1
Mountaineer               1
ML Class                  1
Aspen                     1
Amanti                    1
Voyager                   1
Rondo                     1
Grand Vitara              1
5-Sep                     1
SX4                       1
Prizm                     1
Classic                   1
Rainier                   1
E-150 Cargo - WAV         1
Veloster                  1
Beetle                    1
i3                        1
Vitara                    1
Silverado 1500 4door      1
Monterey                  1
L300                      1
6-series Gran Coupe       1
Q45                       1
Cadenza                   1
SL2                       1
Metris                    1
Fusion Hybrid             1
FR-S                      1
Name: vehicle_model, Length: 368, dtype: int64

Here we assume all the model is the correct input (as we observe 5-Sep, which might be some error input). It could be further improved by cross-validating against external data sources.

In [10]:
# Example for Histogram
import matplotlib.pyplot as plt
temp1 = data['signup_channel'].value_counts(ascending=True)
fig = plt.figure(figsize=(8,4))
ax1 = fig.add_subplot(121)
ax1.set_xlabel('SignUp_Channel')
ax1.set_ylabel('Count of SignUp')
ax1.set_title("Signup by Channel")
temp1.plot(kind='bar')
plt.show()

## Input Data Encoding

#### Check Month for Datetime Binning

In [11]:
def _check_month(column_name):
    num_null = data[column_name].isnull().sum()
    print 'Number of Missing values for '+column_name+': %d'%num_null
    temp_month = data[column_name][data[column_name].notnull()].apply(lambda x: x.split('/')[0])
    print('Frequency Table for Month of '+column_name)
    return temp_month.value_counts()

In [12]:
_check_month('signup_date')

Number of Missing values for signup_date: 0
Frequency Table for Month of signup_date

1    54681
Name: signup_date, dtype: int64

In [13]:
_check_month('bgc_date')

Number of Missing values for bgc_date: 21785
Frequency Table for Month of bgc_date

1    23513
2     9335
3       48
Name: bgc_date, dtype: int64

In [14]:
_check_month('vehicle_added_date')

Number of Missing values for vehicle_added_date: 41547
Frequency Table for Month of vehicle_added_date

1    7531
2    5560
3      43
Name: vehicle_added_date, dtype: int64

#### Binning the Datetime

In [15]:
# Date Binning based on every ten days
data['signup_date'] = data['signup_date'][data.signup_date.notnull()].apply(lambda x: int(x.split('/')[1]))
bins = [1, 10, 20, 31]
group_names = ['first_10d', 'middle_10d', 'last_10d']
data['signup_date'] = pd.cut(data['signup_date'], bins, labels=group_names)

In [16]:
def _datetime_binning_on_Month(column_name):
    data[column_name] = data[column_name][data[column_name].notnull()].apply(lambda x: x.split('/')[0])
    print('Datetime successfully binned for '+column_name)
    
_datetime_binning_on_Month('bgc_date')
_datetime_binning_on_Month('vehicle_added_date')

Datetime successfully binned for bgc_date
Datetime successfully binned for vehicle_added_date

In [17]:
data.head(20)
# data.shape

,id,city_name,signup_os,signup_channel,signup_date,bgc_date,vehicle_added_date,vehicle_make,vehicle_model,vehicle_year,first_completed_date
0,1,Strark,ios web,Paid,first_10d,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Strark,windows,Paid,last_10d,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Wrouver,windows,Organic,middle_10d,1,NaN,NaN,NaN,NaN,NaN
3,4,Berton,android web,Referral,last_10d,2,2,Toyota,Corolla,2016.0,2/3/16
4,5,Strark,android web,Referral,first_10d,1,1,Hyundai,Sonata,2016.0,NaN
5,6,Strark,android web,Referral,middle_10d,1,1,Cadillac,DTS,2006.0,NaN
6,7,Strark,ios web,Paid,middle_10d,1,1,Toyota,Prius V,2014.0,1/23/16
7,8,Strark,ios web,Referral,last_10d,2,NaN,NaN,NaN,NaN,NaN
8,9,Strark,NaN,Referral,first_10d,NaN,NaN,NaN,NaN,NaN,NaN
9,10,Berton,ios web,Paid,last_10d,NaN,NaN,NaN,NaN,NaN,NaN
10,11,Strark,ios web,Referral,middle_10d,2,2,Kia,Optima,2015.0,NaN
11,12,Berton,mac,Paid,first_10d,NaN,NaN,NaN,NaN,NaN,NaN
12,13,Strark,android web,Referral,middle_10d,1,1,Kia,Optima,2015.0,1/28/16
13,14,Strark,ios web,Paid,middle_10d,1,NaN,NaN,NaN,NaN,NaN
14,15,Strark,windows,Paid,first_10d,1,NaN,NaN,NaN,NaN,NaN
15,16,Strark,windows,Referral,middle_10d,1,1,Toyota,Prius V,2015.0,1/16/16
16,17,Wrouver,ios web,Paid,last_10d,NaN,NaN,NaN,NaN,NaN,NaN
17,18,Strark,android web,Paid,last_10d,1,NaN,NaN,NaN,NaN,NaN
18,19,Berton,ios web,Organic,middle_10d,1,NaN,NaN,NaN,NaN,NaN
19,20,Strark,ios web,Organic,first_10d,NaN,NaN,NaN,NaN,NaN,NaN

#### One Hoc Encoding

In [18]:
encode_list = ['city_name', 'signup_os', 'signup_channel', 'signup_date', 'bgc_date', 'vehicle_added_date', 'vehicle_make', 'vehicle_model', 'vehicle_year']
def one_hoc_encoder(data, column_list):
    for column in column_list:
        data = pd.get_dummies(data, prefix=column, columns=[column])
    return data
data = one_hoc_encoder(data, encode_list)

In [19]:
data.columns

Index([u'id', u'first_completed_date', u'city_name_Berton',
       u'city_name_Strark', u'city_name_Wrouver', u'signup_os_android web',
       u'signup_os_ios web', u'signup_os_mac', u'signup_os_other',
       u'signup_os_windows',
       ...
       u'vehicle_year_2008.0', u'vehicle_year_2009.0', u'vehicle_year_2010.0',
       u'vehicle_year_2011.0', u'vehicle_year_2012.0', u'vehicle_year_2013.0',
       u'vehicle_year_2014.0', u'vehicle_year_2015.0', u'vehicle_year_2016.0',
       u'vehicle_year_2017.0'],
      dtype='object', length=460)

In [20]:
# assuming all the null in "first_completed_date" are those not complete the first drive, but not missing value
data.first_completed_date = data.first_completed_date.isnull()

In [21]:
data.head(20)

,id,first_completed_date,city_name_Berton,city_name_Strark,city_name_Wrouver,signup_os_android web,signup_os_ios web,signup_os_mac,signup_os_other,signup_os_windows,...,vehicle_year_2008.0,vehicle_year_2009.0,vehicle_year_2010.0,vehicle_year_2011.0,vehicle_year_2012.0,vehicle_year_2013.0,vehicle_year_2014.0,vehicle_year_2015.0,vehicle_year_2016.0,vehicle_year_2017.0
0,1,True,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,True,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,3,True,0,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,4,False,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,5,True,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
5,6,True,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,7,False,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
7,8,True,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,9,True,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9,10,True,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,11,True,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
11,12,True,1,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
12,13,False,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
13,14,True,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
14,15,True,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
15,16,False,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,1,0,0
16,17,True,0,0,1,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
17,18,True,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,19,True,1,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,20,True,0,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

## Modeling

In [22]:
train, test = train_test_split(data, test_size = 0.3)
x_train = train.drop(['id', 'first_completed_date'], axis = 1)
y_train = train.first_completed_date
x_test = test.drop(['id', 'first_completed_date'], axis = 1)
y_test = test.first_completed_date
print x_train.shape
print y_train.shape
print x_test.shape
print y_test.shape

(38276, 458)
(38276L,)
(16405, 458)
(16405L,)

In [23]:
# from sklearn.pipeline import Pipeline
# from sklearn.preprocessing import PolynomialFeatures, StandardScaler
# from sklearn.svm import LinearSVC
# polynomial_svm_clf = Pipeline((
#         ("poly_features", PolynomialFeatures(degree=10)),
#         ("scaler", StandardScaler()),
#         ("svm_clf", LinearSVC(C=10, loss="hinge"))
#     ))
# polynomial_svm_clf.fit(x_train, y_train)

In [26]:
def modelfit(alg, dtrain, predictors,useTrainCV=True, cv_folds=5, early_stopping_rounds=50):
    
    if useTrainCV:
        xgb_param = alg.get_xgb_params()
        xgtrain = xgb.DMatrix(dtrain[predictors].values, label=dtrain[target].values)
        cvresult = xgb.cv(xgb_param, xgtrain, num_boost_round=alg.get_params()['n_estimators'], nfold=cv_folds,
            metrics='auc', early_stopping_rounds=early_stopping_rounds, show_progress=False)
        alg.set_params(n_estimators=cvresult.shape[0])
    
    #Fit the algorithm on the data
    alg.fit(dtrain[predictors], dtrain['Disbursed'],eval_metric='auc')
        
    #Predict training set:
    dtrain_predictions = alg.predict(dtrain[predictors])
    dtrain_predprob = alg.predict_proba(dtrain[predictors])[:,1]
        
    #Print model report:
    print "\nModel Report"
    print "Accuracy : %.4g" % metrics.accuracy_score(dtrain['Disbursed'].values, dtrain_predictions)
    print "AUC Score (Train): %f" % metrics.roc_auc_score(dtrain['Disbursed'], dtrain_predprob)
                    
    feat_imp = pd.Series(alg.booster().get_fscore()).sort_values(ascending=False)
    feat_imp.plot(kind='bar', title='Feature Importances')
    plt.ylabel('Feature Importance Score')

In [27]:
#Choose all predictors except target & IDcols
# predictors = [x for x in train.columns if x not in [target, IDcol]]
import xgboost as xgb
from xgboost.sklearn import XGBClassifier

xgb1 = XGBClassifier(
 learning_rate =0.1,
 n_estimators=1000,
 max_depth=5,
 min_child_weight=1,
 gamma=0,
 subsample=0.8,
 colsample_bytree=0.8,
 objective= 'binary:logistic',
 nthread=4,
 scale_pos_weight=1,
 seed=27)

ImportError: No module named xgboost.sklearn

In [ ]:
modelfit(xgb1, x_train, y_train)

In [30]:
import xgboost

WindowsError: [Error 126] The specified module could not be found